import { Post, Story, User } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'alex_creative',
    displayName: 'Alex Thompson',
    avatar: 'https://i.pravatar.cc/150?u=alex',
    bio: 'Digital artist & photographer 📸',
    followers: 1234,
    following: 567,
    posts: 89,
    verified: true,
    createdAt: new Date('2023-01-15'),
  },
  {
    id: '2',
    username: 'sarah_wanderer',
    displayName: 'Sarah Chen',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    bio: 'Travel enthusiast ✈️ | Food lover 🍜',
    followers: 2345,
    following: 432,
    posts: 156,
    createdAt: new Date('2023-02-20'),
  },
  {
    id: '3',
    username: 'mike_musician',
    displayName: 'Mike Rodriguez',
    avatar: 'https://i.pravatar.cc/150?u=mike',
    bio: '🎸 Guitarist | 🎵 Music Producer',
    followers: 5678,
    following: 234,
    posts: 234,
    verified: true,
    createdAt: new Date('2023-03-10'),
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    userId: '1',
    user: mockUsers[0],
    content: 'Just captured this amazing sunset! 🌅 The colors were absolutely breathtaking.',
    media: [
      {
        id: 'm1',
        type: 'image',
        uri: 'https://picsum.photos/400/600?random=1',
        width: 400,
        height: 600,
      },
    ],
    position: { x: 200, y: 300 },
    likes: 234,
    comments: 12,
    shares: 5,
    isLiked: false,
    createdAt: new Date(Date.now() - 3600000),
    tags: ['#sunset', '#photography', '#nature'],
  },
  {
    id: '2',
    userId: '2',
    user: mockUsers[1],
    content: 'Found this hidden gem cafe in Tokyo! ☕️✨',
    media: [
      {
        id: 'm2',
        type: 'image',
        uri: 'https://picsum.photos/400/400?random=2',
        width: 400,
        height: 400,
      },
    ],
    position: { x: 600, y: 200 },
    likes: 456,
    comments: 34,
    shares: 12,
    isLiked: true,
    createdAt: new Date(Date.now() - 7200000),
    tags: ['#tokyo', '#cafe', '#travel'],
  },
  {
    id: '3',
    userId: '3',
    user: mockUsers[2],
    content: 'New track dropping soon! 🎶 Stay tuned...',
    media: [
      {
        id: 'm3',
        type: 'video',
        uri: 'https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4',
        thumbnailUri: 'https://picsum.photos/400/400?random=3',
        duration: 30,
        width: 400,
        height: 400,
      },
    ],
    position: { x: 400, y: 600 },
    likes: 789,
    comments: 56,
    shares: 23,
    isLiked: false,
    createdAt: new Date(Date.now() - 10800000),
    tags: ['#music', '#newrelease', '#producer'],
  },
  {
    id: '4',
    userId: '1',
    user: mockUsers[0],
    content: 'Working on a new digital art piece. What do you think? 🎨',
    media: [
      {
        id: 'm4',
        type: 'image',
        uri: 'https://picsum.photos/500/700?random=4',
        width: 500,
        height: 700,
      },
    ],
    position: { x: 800, y: 400 },
    likes: 567,
    comments: 45,
    shares: 18,
    isLiked: true,
    createdAt: new Date(Date.now() - 14400000),
    tags: ['#digitalart', '#creative', '#artwork'],
  },
  {
    id: '5',
    userId: '2',
    user: mockUsers[1],
    content: 'Street food in Bangkok is incredible! 🍜🌶️',
    media: [
      {
        id: 'm5',
        type: 'image',
        uri: 'https://picsum.photos/400/500?random=5',
        width: 400,
        height: 500,
      },
    ],
    position: { x: 300, y: 800 },
    likes: 890,
    comments: 67,
    shares: 29,
    isLiked: false,
    createdAt: new Date(Date.now() - 18000000),
    tags: ['#bangkok', '#streetfood', '#foodie'],
  },
];

export const mockStories: Story[] = [
  {
    id: 's1',
    userId: '1',
    user: mockUsers[0],
    media: {
      id: 'sm1',
      type: 'image',
      uri: 'https://picsum.photos/400/700?random=10',
      width: 400,
      height: 700,
    },
    viewers: [],
    createdAt: new Date(Date.now() - 3600000),
    expiresAt: new Date(Date.now() + 82800000),
  },
  {
    id: 's2',
    userId: '2',
    user: mockUsers[1],
    media: {
      id: 'sm2',
      type: 'image',
      uri: 'https://picsum.photos/400/700?random=11',
      width: 400,
      height: 700,
    },
    viewers: ['1'],
    createdAt: new Date(Date.now() - 7200000),
    expiresAt: new Date(Date.now() + 79200000),
  },
  {
    id: 's3',
    userId: '3',
    user: mockUsers[2],
    media: {
      id: 'sm3',
      type: 'video',
      uri: 'https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4',
      thumbnailUri: 'https://picsum.photos/400/700?random=12',
      duration: 15,
      width: 400,
      height: 700,
    },
    viewers: [],
    createdAt: new Date(Date.now() - 10800000),
    expiresAt: new Date(Date.now() + 75600000),
  },
];